export enum PurchaseStatus {
    PURCHASE_APPROVED = 'PURCHASE_APPROVED',
    PURCHASE_NOT_APPROVED = 'PURCHASE_NOT_APPROVED',
    PLANO_NOT_APPROVED = 'PURCHASE_APPROVED_AND_PLANO_NOT_APPROVED',
    BOLETO_PAYMENT_NOT_APPROVED_YET = 'BOLETO_PAYMENT_NOT_APPROVED_YET',
}